# Dall'immagine iniziale di Cheshire cat
FROM ghcr.io/cheshire-cat-ai/core:latest

#TEST DA CONTROLLARE PRIMA DI USARLO
#installazione delle librerie negessarie
RUN apt get install python3-pip &&\
    python3-pip install requests &&\
    python3-pip install beautifulsoup4

